In [15]:
import pandas as pd   # For data manipulation and analysis
import numpy as np  # For numerical operations
from sklearn.preprocessing import MinMaxScaler #For normalizing numerical columns
from sklearn.preprocessing import LabelEncoder

In [4]:
dataset = pd.read_csv("melb_data.csv")

In [7]:
dataset.shape # Display number of rows and columns in the dataset

(13580, 21)

In [6]:
dataset.head() # Display top 5 rows of the dataset

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [8]:
dataset.info()  # Check data types and non-null counts for each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  object
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 2.2+ MB

In [6]:
dataset.columns # display all the colunms

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [7]:
dataset.describe() #gives the MIN,MAX,MEAN of dataset

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

In [8]:
dataset['Car'].isnull().sum() #find is there any null values or not and then display total no. of null values

np.int64(62)

In [9]:
dataset['Car'].mean() # gives the means of only Car subset

np.float64(1.6100754549489569)

In [10]:
dataset.fillna({'Car':dataset['Car'].mean()},inplace=True) #replcae the null values with the mean

In [9]:
dataset['Address']=dataset['Address'].astype("string")  # Convert Address column to string

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         13580 non-null  object
 1   Address        13580 non-null  string
 2   Rooms          13580 non-null  int64
 3   Type           13580 non-null  object
 4   Price          13580 non-null  float64
 5   Method         13580 non-null  object
 6   SellerG        13580 non-null  object
 7   Date           13580 non-null  object
 8   Distance       13580 non-null  float64
 9   Postcode       13580 non-null  float64
 10  Bedroom2       13580 non-null  float64
 11  Bathroom       13580 non-null  float64
 12  Car            13518 non-null  float64
 13  Landsize       13580 non-null  float64
 14  BuildingArea   7130 non-null   float64
 15  YearBuilt      8205 non-null   float64
 16  CouncilArea    12211 non-null  object
 17  Lattitude      13580 non-null  float64
 18  Longtitude     13580 non-null  float64
 19  Regionname     13580 non-null  object
 20  Propertycount  13580 non-null  float64
dtypes: float64(12), int64(1), object(7), string(1)
memory usage: 2.2+ MB

In [13]:
dataset.duplicated().sum() #display all the duplicated values with sum

np.int64(0)

In [14]:
dataset['Suburb']=dataset['Suburb'].astype("string")

In [15]:
dataset['SellerG']=dataset['SellerG'].astype("string")

In [16]:
dataset['Type']=dataset['Type'].astype("string")

In [17]:
dataset['Date']=dataset['Date'].astype("datetime64[ns]")

In [18]:
dataset.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,2016-03-12,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,2016-04-02,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,2017-04-03,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,2017-04-03,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,2016-04-06,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [19]:
dataset['CouncilArea']=dataset['CouncilArea'].astype("string")

In [20]:
dataset['CouncilArea']=dataset['CouncilArea'].astype("string")

In [21]:
dataset['Method']=dataset['Method'].astype("string")

In [11]:
dataset['Type'].unique()# Display unique values of 'Type' column

array(['h', 'u', 't'], dtype=object)

In [25]:
scaler = MinMaxScaler() #normalizes numerical columns
num_cols = ['Price', 'Distance', 'Landsize', 'BuildingArea']# Select numeric columns to scale
dataset[num_cols] = scaler.fit_transform(dataset[num_cols]) # Apply Min-Max Scaling

In [12]:
dataset[['Price', 'Distance', 'Landsize', 'BuildingArea']].head() # View scaled values

       Price  Distance  Landsize  BuildingArea
0  1480000.0       2.5     202.0           NaN
1  1035000.0       2.5     156.0          79.0
2  1465000.0       2.5     134.0         150.0
3   850000.0       2.5      94.0           NaN
4  1600000.0       2.5     120.0         142.0

In [27]:
# Convert categorical columns into numeric using one-hot encoding
dataset = pd.get_dummies(
    dataset,
    columns=['Type', 'Method', 'Regionname'],
    drop_first=True
)

In [28]:
print(dataset.head())

       Suburb           Address  Rooms     Price SellerG       Date  Distance  \
0  Abbotsford      85 Turner St      2  0.156478  Biggin 2016-03-12  0.051975
1  Abbotsford   25 Bloomburg St      2  0.106562  Biggin 2016-04-02  0.051975
2  Abbotsford      5 Charles St      3  0.154795  Biggin 2017-04-03  0.051975
3  Abbotsford  40 Federation La      3  0.085810  Biggin 2017-04-03  0.051975
4  Abbotsford       55a Park St      4  0.169938  Nelson 2016-04-06  0.051975

   Postcode  Bedroom2  Bathroom  ...  Method_SA  Method_SP  Method_VB  \
0    3067.0       2.0       1.0  ...      False      False      False
1    3067.0       2.0       1.0  ...      False      False      False
2    3067.0       3.0       2.0  ...      False       True      False
3    3067.0       3.0       2.0  ...      False      False      False
4    3067.0       3.0       1.0  ...      False      False       True

   Regionname_Eastern Victoria Regionname_Northern Metropolitan  \
0                        False                             True
1                        False                             True
2                        False                             True
3                        False                             True
4                        False                             True

   Regionname_Northern Victoria  Regionname_South-Eastern Metropolitan  \
0                         False                                  False
1                         False                                  False
2                         False                                  False
3                         False                                  False
4                         False                                  False

   Regionname_Southern Metropolitan  Regionname_Western Metropolitan  \
0                             False                            False
1                             False                            False
2                             False                            False
3                             False                            False
4                             False                            False

   Regionname_Western Victoria
0                        False
1                        False
2                        False
3                        False
4                        False

[5 rows x 31 columns]

In [16]:
le = LabelEncoder()

In [17]:
dataset['Type_encoded'] = le.fit_transform(dataset['Type'])

In [18]:
dataset[['Type', 'Type_encoded']].head()

  Type  Type_encoded
0    h             0
1    h             0
2    h             0
3    h             0
4    h             0