In [49]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [25]:
ds=pd.read_csv("nba.csv")

In [26]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [27]:
ds.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [7]:
ds.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [8]:
ds["Age"].fillna(ds['Age'].mean(),inplace=True)

In [9]:
ds['Position'] = ds['Position'].astype('string')

In [10]:
ds['Age']=ds['Age'].astype('int')

In [11]:
ds['College'].fillna('Unknown',inplace=True)

In [12]:
ds["Salary"].fillna(ds['Salary'].mean(),inplace=True)

In [13]:
ds.isnull().sum()

Name        1
Team        1
Number      1
Position    1
Age         0
Height      1
Weight      1
College     0
Salary      0
dtype: int64

In [14]:
ds.dropna(subset=['Name','Team','Number','Position','Height','Weight'],inplace=True)

In [15]:
ds.isnull().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [28]:
ds['Name'] = ds['Name'].astype('string')

In [29]:
ds['Team'] = ds['Team'].astype('string')

In [30]:
ds['Position'] = ds['Position'].astype('string')

In [31]:
ds['College'] = ds['College'].astype('string')

In [32]:
ds.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,<NA>,5000000.0

In [33]:
ds.dtypes

Name        string[python]
Team        string[python]
Number             float64
Position    string[python]
Age                float64
Height              object
Weight             float64
College     string[python]
Salary             float64
dtype: object

In [36]:
height_groups = ds.groupby(ds["Height"]) #Group all who have the same height together.
height_groups.head() #From each height group, show me the first few rows

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,<NA>,5000000.0
...,...,...,...,...,...,...,...,...,...
275,Alexis Ajinca,New Orleans Pelicans,42.0,C,28.0,7-2,248.0,<NA>,4389607.0
302,Boban Marjanovic,San Antonio Spurs,40.0,C,27.0,7-3,290.0,<NA>,1200000.0
322,Walter Tavares,Atlanta Hawks,22.0,C,24.0,7-3,260.0,<NA>,1000000.0
329,Spencer Hawes,Charlotte Hornets,0.0,PF,28.0,7-1,245.0,Washington,6110034.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,<NA>,2900000.0

In [37]:
height_groups["Salary"].describe() #For each height, give me a summary of salaries

,count,mean,std,min,25%,50%,75%,max
Height,,,,,,,,
5-11,3.0,5.891553e+05,7.926627e+05,55722.0,133733.0,211744.0,855872.00,1500000.0
5-9,1.0,6.912869e+06,NaN,6912869.0,6912869.0,6912869.0,6912869.00,6912869.0
6-0,10.0,5.784075e+06,6.337144e+06,947276.0,2437500.0,3934473.5,4846419.25,21468695.0
6-1,16.0,5.217919e+06,4.286013e+06,700902.0,1646160.0,3402626.5,8633372.75,13500000.0
6-10,45.0,5.200605e+06,5.176373e+06,222888.0,1035000.0,3750000.0,7070730.00,19689000.0
6-11,40.0,6.544397e+06,6.906416e+06,245177.0,1362370.0,3107656.0,11438043.25,22359364.0
6-2,14.0,3.335362e+06,3.861320e+06,525093.0,947276.0,1223469.0,4509231.75,13437500.0
6-3,31.0,5.884952e+06,5.848304e+06,189455.0,1305043.0,3000000.0,9150000.00,20093064.0
6-4,29.0,4.646163e+06,5.275308e+06,134215.0,1015421.0,2525160.0,5192520.00,20000000.0
6-5,31.0,4.377241e+06,4.181469e+06,55722.0,1159920.0,3102240.0,6030303.00,16407500.0
6-6,41.0,3.556182e+06,4.570697e+06,167406.0,947276.0,1749840.0,4088019.00,25000000.0
6-7,44.0,3.473986e+06,4.383151e+06,30888.0,947276.0,1492533.5,3665437.75,16407500.0
6-8,43.0,5.950412e+06,6.133934e+06,83397.0,1259700.0,3425510.0,9321234.00,22970500.0
6-9,57.0,4.133756e+06,4.595223e+06,111444.0,1007026.0,2500000.0,5500000.00,20158622.0
7-0,27.0,5.287712e+06,4.675298e+06,947276.0,2003580.0,4204200.0,7574380.00,19689000.0
7-1,7.0,7.400988e+06,6.587462e+06,1175880.0,3441500.0,4950000.0,9555017.00,19688000.0
7-2,3.0,6.835639e+06,7.825718e+06,525093.0,2457350.0,4389607.0,9990912.00,15592217.0
7-3,4.0,2.307930e+06,1.484918e+06,1000000.0,1150000.0,2050000.0,3207930.00,4131720.0

In [38]:
ds["Age"].max() #max age

40.0

In [50]:
ds["Age"].min() #min age

19.0

In [43]:
bins = [19,25,31,36,40] #create a list of numbers
labels = ["19-24", "25-30", "31-35", "36-40"] #names given to each range
ds["AgeGroup"] = pd.cut(ds["Age"], bins=bins, labels=labels)# Create an AgeGroup column by placing each player's age into labeled age ranges

In [44]:
ds["AgeGroup"].value_counts() #counts how many players falls into each groups

AgeGroup
19-24    197
25-30    189
31-35     56
36-40     13
Name: count, dtype: int64

In [47]:
age_groups = ds.groupby("AgeGroup") #group the dataset by AgeGroup

/tmp/ipykernel_5481/552981331.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  age_groups = ds.groupby("AgeGroup")

In [51]:
age_groups["Salary"].describe() #shows the summary of salary

,count,mean,std,min,25%,50%,75%,max
AgeGroup,,,,,,,,
19-24,192.0,2.994943e+06,3.586630e+06,30888.0,947276.0,1592160.0,3303638.25,16407501.0
25-30,185.0,6.674221e+06,5.882473e+06,55722.0,1474440.0,5000000.0,10300000.00,22970500.0
31-35,55.0,5.117931e+06,5.332386e+06,200600.0,1198231.5,3542500.0,6400000.00,22875000.0
36-40,12.0,5.394166e+06,6.795912e+06,222888.0,947613.5,3732009.5,6020833.50,25000000.0